<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Deep Reinforcement Learning for Power Grid Topology Control – DRL for Power Grid Topology Control</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ea1971949f186b5d7ecce1fd3cf000e4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DRL for Power Grid Topology Control</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">Research Overview</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#research-question" id="toc-research-question" class="nav-link active" data-scroll-target="#research-question">Research question</a></li>
  <li><a href="#test-system" id="toc-test-system" class="nav-link" data-scroll-target="#test-system">Test system</a></li>
  <li><a href="#drl-topology-control-framework" id="toc-drl-topology-control-framework" class="nav-link" data-scroll-target="#drl-topology-control-framework">DRL topology-control framework</a></li>
  <li><a href="#action-space-design" id="toc-action-space-design" class="nav-link" data-scroll-target="#action-space-design">Action-space design</a></li>
  <li><a href="#methods-compared" id="toc-methods-compared" class="nav-link" data-scroll-target="#methods-compared">Methods compared</a></li>
  <li><a href="#shared-reward-and-experimental-settings" id="toc-shared-reward-and-experimental-settings" class="nav-link" data-scroll-target="#shared-reward-and-experimental-settings">Shared reward and experimental settings</a></li>
  <li><a href="#how-each-controller-makes-decisions" id="toc-how-each-controller-makes-decisions" class="nav-link" data-scroll-target="#how-each-controller-makes-decisions">How each controller makes decisions</a></li>
  <li><a href="#why-did-the-methods-behave-differently" id="toc-why-did-the-methods-behave-differently" class="nav-link" data-scroll-target="#why-did-the-methods-behave-differently">Why did the methods behave differently?</a></li>
  <li><a href="#evaluation-metrics" id="toc-evaluation-metrics" class="nav-link" data-scroll-target="#evaluation-metrics">Evaluation metrics</a></li>
  <li><a href="#key-results" id="toc-key-results" class="nav-link" data-scroll-target="#key-results">Key results</a></li>
  <li><a href="#detailed-performance" id="toc-detailed-performance" class="nav-link" data-scroll-target="#detailed-performance">Detailed performance</a></li>
  <li><a href="#mechanism-level-diagnostic-analysis" id="toc-mechanism-level-diagnostic-analysis" class="nav-link" data-scroll-target="#mechanism-level-diagnostic-analysis">Mechanism-level diagnostic analysis</a></li>
  <li><a href="#interpretation-limits-and-next-validation-steps" id="toc-interpretation-limits-and-next-validation-steps" class="nav-link" data-scroll-target="#interpretation-limits-and-next-validation-steps">Interpretation limits and next validation steps</a></li>
  <li><a href="#main-findings" id="toc-main-findings" class="nav-link" data-scroll-target="#main-findings">Main findings</a></li>
  <li><a href="#research-message" id="toc-research-message" class="nav-link" data-scroll-target="#research-message">Research message</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Deep Reinforcement Learning for Power Grid Topology Control</h1>
<p class="subtitle lead">Benchmarking topology reconfiguration for secure and efficient grid operation</p>
</div>



<div class="quarto-title-meta column-page-left">

    
  
    
  </div>
  


</header>


<div class="hero">
<div class="hero-kicker">
POWER GRID · DEEP REINFORCEMENT LEARNING · TOPOLOGY CONTROL
</div>
<section id="deep-reinforcement-learning-for-power-grid-topology-control" class="level1">
<h1>Deep Reinforcement Learning for Power Grid Topology Control</h1>
<p class="hero-subtitle">
This study evaluates whether deep reinforcement learning can improve power-grid security by changing substation busbar connections, redistributing power flows, and reducing transmission-line overloads.
</p>
<div class="metric-grid">
<div class="metric-card">
<div class="metric-value">
IEEE 14-bus
</div>
<div class="metric-label">
Test system
</div>
</div>
<div class="metric-card">
<div class="metric-value">
5 min
</div>
<div class="metric-label">
Decision interval
</div>
</div>
<div class="metric-card">
<div class="metric-value">
21
</div>
<div class="metric-label">
Available actions
</div>
</div>
<div class="metric-card">
<div class="metric-value">
95%
</div>
<div class="metric-label">
Best DRL completion rate
</div>
</div>
</div>
</section>
</div>
<section id="research-question" class="level2">
<h2 class="anchored" data-anchor-id="research-question">Research question</h2>
<p>Power generation and load demand vary over time, which can create highly loaded operating conditions.</p>
<section id="conceptual-correction-market-redispatch-is-not-topology-control" class="level3">
<h3 class="anchored" data-anchor-id="conceptual-correction-market-redispatch-is-not-topology-control">Conceptual correction: market redispatch is not topology control</h3>
<p>An initial assumption was that PJM congestion management and substation topology control were the same process. <strong>That assumption was incorrect.</strong> PJM primarily uses security-constrained generation redispatch, which changes nodal power injections while normally retaining the network topology. In contrast, this study changes busbar connections while the agent does not directly control generation or demand. Both approaches redistribute line flows, but through different control variables. Machine learning and DRL are decision-making tools, not the research problem.</p>
<p>The fundamental research question is therefore:</p>
<blockquote class="blockquote">
<p><strong>To what extent can substation topology reconfiguration mitigate transmission-line overloads and maintain secure operation under time-varying generation and demand, without directly redispatching generation or shedding load?</strong></p>
</blockquote>
<p>DRL is evaluated as one method for selecting topology actions and is compared with Greedy action-by-action search. These actions do not add transmission lines; they only change existing busbar connections.</p>
</section>
<section id="how-a-busbar-switching-action-changes-power-flow" class="level3">
<h3 class="anchored" data-anchor-id="how-a-busbar-switching-action-changes-power-flow">How a busbar-switching action changes power flow</h3>
<p>The example below illustrates the physical meaning of one topology-control action. Before switching, all equipment is connected to Busbar 1 and Line C is overloaded. The action moves the terminals of Line A and Line B to Busbar 2 while leaving the generator, load, and Line C on Busbar 1. Splitting the original electrical node changes the available flow paths, so the power-flow solution and line-loading ratios are redistributed.</p>
<div class="figure-panel">
<p><img src="images/busbar_switching_powerflow.svg" class="img-fluid" style="width:100.0%" alt="Illustrative comparison of power flows before and after transferring Line A and Line B from Busbar 1 to Busbar 2 within a substation"></p>
</div>
<div class="mini-note">
<p><strong>Illustrative example:</strong> the MW values in this diagram explain the switching mechanism and satisfy nodal power balance; they are not measurements from a reported Case14 test action. The action changes existing electrical connections and does not add a new transmission line.</p>
</div>
</section>
</section>
<section id="test-system" class="level2">
<h2 class="anchored" data-anchor-id="test-system">Test system</h2>
<p>The study uses the IEEE 14-bus power grid implemented in <strong>Grid2Op</strong>. It contains 14 substations, 20 transmission lines, 6 generators, and 11 loads. Power generation and load demand change every five minutes.</p>
<div class="figure-panel">
<p><img src="images/case14_topology.png" class="img-fluid" style="width:100.0%" alt="Grid2Op Case14 topology showing substations, transmission lines, generators, and loads"></p>
</div>
<div class="mini-note">
<p><strong>Episode definition:</strong> each episode represents seven days, corresponding to 2,016 five-minute time steps.</p>
</div>
</section>
<section id="drl-topology-control-framework" class="level2">
<h2 class="anchored" data-anchor-id="drl-topology-control-framework">DRL topology-control framework</h2>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    A["Current grid state"] --&gt; B["DRL agent"]
    B --&gt; C["Select one of 21 actions"]
    C --&gt; D["Change busbar connection&lt;br/&gt;or Do Nothing"]
    D --&gt; E["Power-flow redistribution"]
    E --&gt; F["Line loading / grid security"]
    F --&gt; A
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>At each time step, the agent observes the current grid state and selects one action. The resulting topology determines how power is redistributed before the next decision.</p>
</section>
<section id="action-space-design" class="level2">
<h2 class="anchored" data-anchor-id="action-space-design">Action-space design</h2>
<p>The action space is fixed before DRL training so that all learning algorithms and the Greedy controller are compared using exactly the same actions.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    A["178 candidate&lt;br/&gt;topology actions"] --&gt; B["Test on 20 highly&lt;br/&gt;loaded grid states"]
    B --&gt; C["Rank by overload reduction&lt;br/&gt;and valid power flow"]
    C --&gt; D["Select best 20&lt;br/&gt;topology actions"]
    D --&gt; E["+ 1 Do-Nothing action"]
    E --&gt; F["21-action&lt;br/&gt;benchmark space"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<section id="where-the-178-candidate-actions-come-from" class="level3">
<h3 class="anchored" data-anchor-id="where-the-178-candidate-actions-come-from">Where the 178 candidate actions come from</h3>
<p>Grid2Op generates topology actions by changing the busbar connections within one substation at a time. Each action represents one possible busbar arrangement for the controllable elements in that substation. Changes at different substations are not combined, and no equipment is disconnected. Because Busbar 1 and Busbar 2 are electrically equivalent, the first element is always assigned to Busbar 1 to avoid generating duplicate arrangements. In addition, each busbar that is used must contain at least one transmission-line connection.</p>
<p>For a substation with <span class="math inline">\(n_s\)</span> connected elements and <span class="math inline">\(m_s\)</span> line endpoints, the formula first counts all valid assignments, including the unchanged state in which every element remains on Busbar 1:</p>
<p><span class="math display">\[
C_s = 2^{n_s-1} - 2^{n_s-m_s} + 1.
\]</span></p>
<p>Grid2Op keeps these assignments as actions only when at least two valid choices exist. If <span class="math inline">\(C_s=1\)</span>, the only choice is the unchanged state, so Grid2Op returns zero actions:</p>
<p><span class="math display">\[
N_s=
\begin{cases}
C_s, &amp; C_s\geq2,\\
0, &amp; C_s=1.
\end{cases}
\]</span></p>
<p>S7 makes this distinction clear. It has two elements but only one line endpoint. A split would leave one busbar without a line connection, so the split is invalid. Its only valid assignment is the unchanged state: <span class="math inline">\(C_7=1\)</span>, but Grid2Op returns <span class="math inline">\(N_7=0\)</span> actions.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Substation</th>
<th style="text-align: right;">Elements (<span class="math inline">\(n_s\)</span>)</th>
<th style="text-align: right;">Line endpoints (<span class="math inline">\(m_s\)</span>)</th>
<th style="text-align: right;">Formula count (<span class="math inline">\(C_s\)</span>)</th>
<th style="text-align: right;">Returned actions (<span class="math inline">\(N_s\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">S0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: right;">S1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">29</td>
</tr>
<tr class="odd">
<td style="text-align: right;">S2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: right;">S3</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">31</td>
</tr>
<tr class="odd">
<td style="text-align: right;">S4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">15</td>
</tr>
<tr class="even">
<td style="text-align: right;">S5</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">57</td>
<td style="text-align: right;">57</td>
</tr>
<tr class="odd">
<td style="text-align: right;">S6</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>S7</strong></td>
<td style="text-align: right;"><strong>2</strong></td>
<td style="text-align: right;"><strong>1</strong></td>
<td style="text-align: right;"><strong>1</strong></td>
<td style="text-align: right;"><strong>0</strong></td>
</tr>
<tr class="odd">
<td style="text-align: right;">S8</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">15</td>
</tr>
<tr class="even">
<td style="text-align: right;">S9</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">S10</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: right;">S11</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">S12</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: right;">S13</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>Total</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"><strong>179</strong></td>
<td style="text-align: right;"><strong>178</strong></td>
</tr>
</tbody>
</table>
<p>In short, the formula counts 179 valid assignments, but S7 contributes only its unchanged state. Removing that non-action leaves 178 usable <strong>single-substation set-bus actions</strong>. This is not the number of all possible full-grid topologies.</p>
</section>
<section id="some-explanations" class="level3">
<h3 class="anchored" data-anchor-id="some-explanations"><span style="color: #c62828;">Some explanations</span></h3>
<section id="what-is-a-chronic" class="level4">
<h4 class="anchored" data-anchor-id="what-is-a-chronic">What is a chronic?</h4>
<p>A chronic is a pre-generated time series of load and generation values at five-minute intervals. The dataset contains 1,004 chronics, divided into 702 for training, 150 for validation, and 152 for testing.</p>
</section>
<section id="how-were-the-stress-states-selected" class="level4">
<h4 class="anchored" data-anchor-id="how-were-the-stress-states-selected">How were the stress states selected?</h4>
<p>Only the training chronics were used. The grid followed Do-Nothing, and a time step was retained when</p>
<p><span class="math display">\[
\max_i(\rho_i) \geq 0.90.
\]</span></p>
<p>The scan stopped after 20 stress states were found. Both 0.90 and 20 are user-defined settings.</p>
</section>
<section id="why-were-only-108-actions-simulated" class="level4">
<h4 class="anchored" data-anchor-id="why-were-only-108-actions-simulated">Why were only 108 actions simulated?</h4>
<p>At each stress state, the three most heavily loaded lines were identified. Only actions at the endpoint substations of these lines were simulated. Across the 20 states, 108 of the 178 available topology actions passed this filter.</p>
<p>For each simulated action, grid risk was measured as</p>
<p><span class="math display">\[
J = \max_i(\rho_i) + 5\sum_i\max(\rho_i-1,0)^2,
\]</span></p>
<p>and its improvement was</p>
<p><span class="math display">\[
\Delta J = \max(J_{\mathrm{before}}-J_{\mathrm{after}},0).
\]</span></p>
<p>A larger <span class="math inline">\(\Delta J\)</span> means a greater one-step reduction in grid risk. Actions were ranked by how often and how strongly they reduced <span class="math inline">\(J\)</span>. The best 20 were retained, and A0 was added to create the final 21-action set. Validation and test chronics were not used.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Number</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1,004</td>
<td>Supplied chronics</td>
</tr>
<tr class="even">
<td style="text-align: right;">20</td>
<td>Training stress states selected</td>
</tr>
<tr class="odd">
<td style="text-align: right;">178</td>
<td>Available topology actions</td>
</tr>
<tr class="even">
<td style="text-align: right;">108</td>
<td>Actions passing the endpoint filter</td>
</tr>
<tr class="odd">
<td style="text-align: right;">20 + A0</td>
<td>Final 21-action catalogue</td>
</tr>
</tbody>
</table>
</section>
<section id="what-is-the-limitation" class="level4">
<h4 class="anchored" data-anchor-id="what-is-the-limitation">What is the limitation?</h4>
<p>The endpoint filter saves computation, but it may exclude useful actions at more distant substations. Because the grid is connected, a distant topology change can still affect line flows. Simulating all 178 actions would give a more complete comparison.</p>
</section>
</section>
<section id="the-fixed-21-action-catalogue" class="level3">
<h3 class="anchored" data-anchor-id="the-fixed-21-action-catalogue">The fixed 21-action catalogue</h3>
<div class="figure-panel">
<p><img src="images/case14_action_catalogue.png" class="img-fluid" style="width:100.0%" alt="Heatmap of the 20 selected Case14 topology actions showing busbar assignments and their training-only ranking scores"></p>
</div>
<p>In panel <strong>a</strong>, blue cells assign a device to Busbar 1, orange cells assign it to Busbar 2, and grey cells indicate a substation unaffected by that action. A line label such as <code>L9@S12</code> denotes the endpoint of Line 9 located at Substation 12. In panel <strong>b</strong>, the lower horizontal axis reports the percentage of the 20 training stress states improved by each action; the upper axis and black diamonds report the mean one-step score reduction.</p>
<p>The table below lists the Busbar 2 members for each action. All other devices at the same substation are explicitly assigned to Busbar 1.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Action</th>
<th style="text-align: right;">Substation</th>
<th>Devices assigned to Busbar 2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">A0</td>
<td style="text-align: right;">—</td>
<td>Do-Nothing; no topology change</td>
</tr>
<tr class="even">
<td style="text-align: right;">A1</td>
<td style="text-align: right;">S4</td>
<td>L17, L1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">A2</td>
<td style="text-align: right;">S12</td>
<td>L9</td>
</tr>
<tr class="even">
<td style="text-align: right;">A3</td>
<td style="text-align: right;">S5</td>
<td>Gen2, Gen3, L7, L9</td>
</tr>
<tr class="odd">
<td style="text-align: right;">A4</td>
<td style="text-align: right;">S1</td>
<td>L2, L4</td>
</tr>
<tr class="even">
<td style="text-align: right;">A5</td>
<td style="text-align: right;">S1</td>
<td>L2, L4, L0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">A6</td>
<td style="text-align: right;">S5</td>
<td>Gen3, L7, L9, L17</td>
</tr>
<tr class="even">
<td style="text-align: right;">A7</td>
<td style="text-align: right;">S4</td>
<td>L17, L6</td>
</tr>
<tr class="odd">
<td style="text-align: right;">A8</td>
<td style="text-align: right;">S4</td>
<td>L1, L4</td>
</tr>
<tr class="even">
<td style="text-align: right;">A9</td>
<td style="text-align: right;">S1</td>
<td>Gen0, L4, L0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">A10</td>
<td style="text-align: right;">S1</td>
<td>Gen0, L3</td>
</tr>
<tr class="even">
<td style="text-align: right;">A11</td>
<td style="text-align: right;">S1</td>
<td>Gen0, L2, L4</td>
</tr>
<tr class="odd">
<td style="text-align: right;">A12</td>
<td style="text-align: right;">S1</td>
<td>L3</td>
</tr>
<tr class="even">
<td style="text-align: right;">A13</td>
<td style="text-align: right;">S5</td>
<td>Gen2, Gen3, L7, L8, L17</td>
</tr>
<tr class="odd">
<td style="text-align: right;">A14</td>
<td style="text-align: right;">S5</td>
<td>Gen3, L7, L17</td>
</tr>
<tr class="even">
<td style="text-align: right;">A15</td>
<td style="text-align: right;">S4</td>
<td>L17, L4</td>
</tr>
<tr class="odd">
<td style="text-align: right;">A16</td>
<td style="text-align: right;">S4</td>
<td>L17, L1, L6</td>
</tr>
<tr class="even">
<td style="text-align: right;">A17</td>
<td style="text-align: right;">S12</td>
<td>Empty; restore all S12 devices to Busbar 1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">A18</td>
<td style="text-align: right;">S5</td>
<td>Empty; restore all S5 devices to Busbar 1</td>
</tr>
<tr class="even">
<td style="text-align: right;">A19</td>
<td style="text-align: right;">S4</td>
<td>Empty; restore all S4 devices to Busbar 1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">A20</td>
<td style="text-align: right;">S1</td>
<td>Empty; restore all S1 devices to Busbar 1</td>
</tr>
</tbody>
</table>
<p>These are set-point actions rather than toggle commands. Repeating an action after its target topology is already active produces another nonzero action request but no new physical switch.</p>
</section>
</section>
<section id="methods-compared" class="level2">
<h2 class="anchored" data-anchor-id="methods-compared">Methods compared</h2>
<div class="method-grid">
<div class="method-card">
<strong>DQN</strong><span>Value-based DRL baseline</span>
</div>
<div class="method-card">
<strong>Double DQN</strong><span>Double-estimator DQN variant</span>
</div>
<div class="method-card">
<strong>Dueling DQN</strong><span>Dueling value–advantage architecture</span>
</div>
<div class="method-card">
<strong>PPO</strong><span>Policy-optimization method</span>
</div>
<div class="method-card">
<strong>A2C</strong><span>Actor–critic method</span>
</div>
<div class="method-card">
<strong>Dueling Double DQN</strong><span>Combined DQN variant</span>
</div>
<div class="method-card baseline">
<strong>Greedy</strong><span>Non-learning baseline</span>
</div>
<div class="method-card baseline">
<strong>Do-Nothing</strong><span>No-control baseline</span>
</div>
</div>
</section>
<section id="shared-reward-and-experimental-settings" class="level2">
<h2 class="anchored" data-anchor-id="shared-reward-and-experimental-settings">Shared reward and experimental settings</h2>
<p>All learning-based controllers receive the same reward after each grid action. The reward is defined in this project rather than supplied by Grid2Op:</p>
<p><span class="math display">\[
\begin{aligned}
r_t ={}&amp; 1
-5\sum_i[\max(\rho_i-0.9,0)]^2
-20\sum_i[\max(\rho_i-1,0)]^2 \\
&amp;-0.05I_{\mathrm{switch}}
-0.5I_{\mathrm{invalid}}
-100I_{\mathrm{blackout}}.
\end{aligned}
\]</span></p>
<p>Here, <span class="math inline">\(\rho_i\)</span> is the loading ratio of line <span class="math inline">\(i\)</span>. The first term rewards each surviving five-minute step. Loading above 90% receives a warning penalty, loading above 100% receives an additional penalty, and actual switching, invalid actions, and blackout are penalized separately.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Reward parameter</th>
<th style="text-align: right;">Value</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Survival reward</td>
<td style="text-align: right;">1.0</td>
<td>Reward one safe five-minute step</td>
</tr>
<tr class="even">
<td>Warning threshold</td>
<td style="text-align: right;">0.90</td>
<td>Start discouraging operation near the thermal limit</td>
</tr>
<tr class="odd">
<td>Warning weight</td>
<td style="text-align: right;">5.0</td>
<td>Control the penalty for <span class="math inline">\(\rho&gt;0.9\)</span></td>
</tr>
<tr class="even">
<td>Overload weight</td>
<td style="text-align: right;">20.0</td>
<td>Add a stronger penalty for <span class="math inline">\(\rho&gt;1\)</span></td>
</tr>
<tr class="odd">
<td>Switching weight</td>
<td style="text-align: right;">0.05</td>
<td>Discourage unnecessary physical switching</td>
</tr>
<tr class="even">
<td>Invalid-action penalty</td>
<td style="text-align: right;">0.5</td>
<td>Penalize illegal or ambiguous commands</td>
</tr>
<tr class="odd">
<td>Blackout penalty</td>
<td style="text-align: right;">100</td>
<td>Strongly penalize terminal grid failure</td>
</tr>
</tbody>
</table>
<p>These weights were selected heuristically to express the priority <code>blackout prevention &gt; overload mitigation &gt; fewer switching operations</code>. They are not physical constants or proven optimal values. A reward-sensitivity study is therefore needed before making a general claim about the best weighting.</p>
<p>The common experiment uses 500,000 training steps, a maximum episode length of 2,016 steps, a thermal-limit scale of 1.05, and a fixed 21-action catalogue. The chronics are split into 70% training, 15% validation, and 15% test sets using split seed 2026. Training seed 0 is used for the reported preliminary models. The best checkpoint is selected on ten validation episodes every 50,000 training steps.</p>
</section>
<section id="how-each-controller-makes-decisions" class="level2">
<h2 class="anchored" data-anchor-id="how-each-controller-makes-decisions">How each controller makes decisions</h2>
<section id="do-nothing" class="level3">
<h3 class="anchored" data-anchor-id="do-nothing">Do-Nothing</h3>
<p>Do-Nothing always selects A0:</p>
<p><span class="math display">\[a_t=A0.\]</span></p>
<p>It has no network, training objective, or learning hyperparameters. Its reported reward is still calculated with the common environment reward. It measures how often the grid can complete seven days without active topology control.</p>
</section>
<section id="greedy" class="level3">
<h3 class="anchored" data-anchor-id="greedy">Greedy</h3>
<p>Greedy is a model-based, one-step controller rather than a DRL method. If the current maximum loading is no greater than 0.90, it selects A0. Otherwise, it uses Grid2Op to simulate each of the 21 actions one step ahead and minimizes</p>
<p><span class="math display">\[
J(s_t,a)=\max_i\rho_{i,t+1}
+5\sum_i[\max(\rho_{i,t+1}-1,0)]^2
+0.01I(a\ne A0).
\]</span></p>
<p>An illegal or immediately terminal simulation receives an additional cost of 1,000. The Greedy score <span class="math inline">\(J\)</span> is used only to select an action; the resulting episode is evaluated with the same environment reward as every other controller.</p>
<section id="greedy-decision-score-versus-common-reward" class="level4">
<h4 class="anchored" data-anchor-id="greedy-decision-score-versus-common-reward">Greedy decision score versus common reward</h4>
<p>The two quantities have different roles. At each five-minute step, Greedy simulates the candidate actions, calculates <span class="math inline">\(J(s_t,a)\)</span> for each simulation, and executes the action with the lowest score:</p>
<p><span class="math display">\[
a_t=\arg\min_a J(s_t,a).
\]</span></p>
<p>The common reward does <strong>not</strong> participate in this choice. It is calculated only after the selected action has been executed in the environment. The step rewards are then summed to report the final episode reward and to compare Greedy with the other methods. Greedy does not use these rewards to update a model.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    A[Current grid state] --&gt; B[Simulate the 21 actions]
    B --&gt; C[Calculate internal score J]
    C --&gt; D[Execute the action with minimum J]
    D --&gt; E[Calculate the common reward]
    E --&gt; F[Accumulate the reported episode reward]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 38%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Quantity</th>
<th style="text-align: center;">Determines the Greedy action?</th>
<th style="text-align: center;">Used in the reported episode reward?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Internal score <span class="math inline">\(J\)</span></td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">No</td>
</tr>
<tr class="even">
<td>Common environment reward <span class="math inline">\(r_t\)</span></td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">Yes</td>
</tr>
</tbody>
</table>
<p>This distinction also separates Greedy from the DRL agents. Greedy directly minimizes a one-step power-flow score, whereas DQN, PPO, and A2C use the common reward during training to learn a policy that seeks higher discounted return.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Greedy parameter</th>
<th style="text-align: right;">Value</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Activation threshold</td>
<td style="text-align: right;">0.90</td>
<td>Avoid simulations while the grid is safely loaded</td>
</tr>
<tr class="even">
<td>Look-ahead horizon</td>
<td style="text-align: right;">1 step</td>
<td>Predict the next five-minute state</td>
</tr>
<tr class="odd">
<td>Candidate actions</td>
<td style="text-align: right;">21</td>
<td>Test the shared action catalogue</td>
</tr>
<tr class="even">
<td>Overload weight</td>
<td style="text-align: right;">5.0</td>
<td>Prefer actions that reduce overload</td>
</tr>
<tr class="odd">
<td>Nonzero-action cost</td>
<td style="text-align: right;">0.01</td>
<td>Prefer A0 when two actions have similar effects</td>
</tr>
<tr class="even">
<td>Illegal/terminal cost</td>
<td style="text-align: right;">1,000</td>
<td>Reject unsafe simulated actions</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="dqn-family" class="level3">
<h3 class="anchored" data-anchor-id="dqn-family">DQN family</h3>
<p>DQN learns the expected discounted return of each state-action pair:</p>
<p><span class="math display">\[Q(s_t,a_t)=\mathbb{E}\left[\sum_{k=0}^{\infty}\gamma^k r_{t+k}\right].\]</span></p>
<p>At evaluation, the network outputs 21 Q-values and selects the largest.</p>
<section id="online-and-target-networks" class="level4">
<h4 class="anchored" data-anchor-id="online-and-target-networks">Online and Target networks</h4>
<p>Every DQN variant in this study contains two Q-networks. They are not two separate agents. They are two copies of the same network architecture with different roles:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Network</th>
<th>Main role</th>
<th>How it changes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Online network</strong></td>
<td>Select actions and learn <span class="math inline">\(Q_{\mathrm{online}}(s,a)\)</span></td>
<td>Updated by gradient descent during training</td>
</tr>
<tr class="even">
<td><strong>Target network</strong></td>
<td>Provide a stable value for the learning target</td>
<td>Held fixed, then replaced by the Online weights every 2,000 steps</td>
</tr>
</tbody>
</table>
<p>The Online network changes frequently. If it were also used as a continuously changing target, learning could become unstable. The delayed Target network makes the target value more stable. During evaluation, only the Online network is needed to select an action:</p>
<p><span class="math display">\[
a_t=\arg\max_a Q_{\mathrm{online}}(s_t,a).
\]</span></p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    S[Current state] --&gt; O[Online network]
    O --&gt; A[Select one of 21 actions]
    O --&gt; L[Huber-loss update]
    T[Target network] --&gt; L
    O -. copy weights every 2,000 steps .-&gt; T
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Standard DQN uses the target</p>
<p><span class="math display">\[
y_t=r_t+\gamma(1-d_t)\max_{a'}Q_{\mathrm{target}}(s_{t+1},a'),
\]</span></p>
<p>and minimizes the Huber loss between <span class="math inline">\(Q_{\mathrm{online}}(s_t,a_t)\)</span> and <span class="math inline">\(y_t\)</span>.</p>
<p>Double DQN lets the online network select the next action and the target network evaluate it:</p>
<p><span class="math display">\[
a^*=\arg\max_{a'}Q_{\mathrm{online}}(s_{t+1},a'),\qquad
y_t=r_t+\gamma(1-d_t)Q_{\mathrm{target}}(s_{t+1},a^*).
\]</span></p>
<p>Dueling DQN changes the output architecture to</p>
<p><span class="math display">\[
Q(s,a)=V(s)+A(s,a)-\frac{1}{21}\sum_{a'}A(s,a'),
\]</span></p>
<p>where <span class="math inline">\(V(s)\)</span> measures the value of the grid state and <span class="math inline">\(A(s,a)\)</span> measures the relative advantage of each action. Dueling Double DQN combines this architecture with the Double DQN target.</p>
<p>All four DQN variants use both networks. Standard DQN and Dueling DQN use the Target network to find the largest next-state Q-value. Double DQN and Dueling Double DQN use the Online network to select the next action and the Target network to evaluate that action. In the Dueling variants, both networks use the same value–advantage architecture. PPO and A2C do not use this Online–Target Q-network pair; they instead use Actor and Critic networks.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>DQN-family parameter</th>
<th style="text-align: right;">Value</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Hidden layers</td>
<td style="text-align: right;">[128, 128], ReLU</td>
<td>Map the observation to 21 action values</td>
</tr>
<tr class="even">
<td>Learning rate</td>
<td style="text-align: right;">0.0001</td>
<td>Set the Adam optimizer update size</td>
</tr>
<tr class="odd">
<td>Discount factor <span class="math inline">\(\gamma\)</span></td>
<td style="text-align: right;">0.99</td>
<td>Control the importance of future rewards</td>
</tr>
<tr class="even">
<td>Replay-buffer size</td>
<td style="text-align: right;">100,000</td>
<td>Store past transitions for reuse</td>
</tr>
<tr class="odd">
<td>Batch size</td>
<td style="text-align: right;">128</td>
<td>Number of replay samples per update</td>
</tr>
<tr class="even">
<td>Learning starts</td>
<td style="text-align: right;">5,000 steps</td>
<td>Fill the replay buffer before learning</td>
</tr>
<tr class="odd">
<td>Training frequency</td>
<td style="text-align: right;">Every 4 steps</td>
<td>Control network-update frequency</td>
</tr>
<tr class="even">
<td>Target update interval</td>
<td style="text-align: right;">2,000 steps</td>
<td>Copy online weights to the target network</td>
</tr>
<tr class="odd">
<td>Gradient limit</td>
<td style="text-align: right;">10.0</td>
<td>Reduce unstable gradient updates</td>
</tr>
<tr class="even">
<td>Exploration <span class="math inline">\(\epsilon\)</span></td>
<td style="text-align: right;">1.0 to 0.05</td>
<td>Move from random exploration to learned actions</td>
</tr>
<tr class="odd">
<td>Exploration decay</td>
<td style="text-align: right;">100,000 steps</td>
<td>Set how quickly <span class="math inline">\(\epsilon\)</span> decreases</td>
</tr>
<tr class="even">
<td>Loss</td>
<td style="text-align: right;">Huber loss</td>
<td>Reduce sensitivity to very large temporal-difference errors</td>
</tr>
</tbody>
</table>
<p>The four variants use the same settings. They differ only in the Double and Dueling switches:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Method</th>
<th style="text-align: center;">Double target</th>
<th style="text-align: center;">Dueling architecture</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DQN</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">No</td>
</tr>
<tr class="even">
<td>Double DQN</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">No</td>
</tr>
<tr class="odd">
<td>Dueling DQN</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">Yes</td>
</tr>
<tr class="even">
<td>Dueling Double DQN</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">Yes</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="ppo" class="level3">
<h3 class="anchored" data-anchor-id="ppo">PPO</h3>
<p>PPO is an on-policy actor–critic method. The actor outputs a probability for each of the 21 actions, while the critic estimates <span class="math inline">\(V(s)\)</span>. Generalized advantage estimation uses <span class="math inline">\(\gamma=0.99\)</span> and <span class="math inline">\(\lambda=0.95\)</span>. PPO limits each policy update with</p>
<p><span class="math display">\[
L_{\mathrm{clip}}=
\mathbb{E}\left[
\min\left(r_t(\theta)\hat A_t,
\operatorname{clip}(r_t(\theta),0.8,1.2)\hat A_t\right)
\right],
\]</span></p>
<p>where <span class="math inline">\(r_t(\theta)\)</span> is the new-to-old action-probability ratio. Its optimization combines the clipped policy objective, a value loss, and an entropy bonus.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>PPO parameter</th>
<th style="text-align: right;">Value</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Hidden layers</td>
<td style="text-align: right;">[128, 128]</td>
<td>Build the actor and critic networks</td>
</tr>
<tr class="even">
<td>Learning rate</td>
<td style="text-align: right;">0.0003</td>
<td>Set the Adam update size</td>
</tr>
<tr class="odd">
<td>Discount factor <span class="math inline">\(\gamma\)</span></td>
<td style="text-align: right;">0.99</td>
<td>Weight future rewards</td>
</tr>
<tr class="even">
<td>GAE <span class="math inline">\(\lambda\)</span></td>
<td style="text-align: right;">0.95</td>
<td>Balance bias and variance in advantage estimates</td>
</tr>
<tr class="odd">
<td>Rollout length</td>
<td style="text-align: right;">1,024 steps</td>
<td>Collect on-policy data before updating</td>
</tr>
<tr class="even">
<td>Batch size</td>
<td style="text-align: right;">128</td>
<td>Split each rollout into mini-batches</td>
</tr>
<tr class="odd">
<td>Epochs per rollout</td>
<td style="text-align: right;">10</td>
<td>Reuse each rollout for ten optimization passes</td>
</tr>
<tr class="even">
<td>Clip range</td>
<td style="text-align: right;">0.20</td>
<td>Limit large policy changes</td>
</tr>
<tr class="odd">
<td>Entropy coefficient</td>
<td style="text-align: right;">0.01</td>
<td>Encourage action exploration</td>
</tr>
<tr class="even">
<td>Value-loss coefficient</td>
<td style="text-align: right;">0.5</td>
<td>Weight critic learning</td>
</tr>
<tr class="odd">
<td>Gradient limit</td>
<td style="text-align: right;">0.5</td>
<td>Stabilize optimization</td>
</tr>
<tr class="even">
<td>Advantage normalization</td>
<td style="text-align: right;">Enabled</td>
<td>Standardize advantages before updating</td>
</tr>
</tbody>
</table>
</section>
<section id="a2c" class="level3">
<h3 class="anchored" data-anchor-id="a2c">A2C</h3>
<p>A2C is also an actor–critic method, but it has no PPO clipping and updates after much shorter rollouts. Its objective can be summarized as</p>
<p><span class="math display">\[
L_{\mathrm{A2C}}=
-\mathbb{E}[\log\pi(a_t|s_t)\hat A_t]
+0.5L_{\mathrm{value}}-0.01H(\pi).
\]</span></p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>A2C parameter</th>
<th style="text-align: right;">Value</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Hidden layers</td>
<td style="text-align: right;">[128, 128]</td>
<td>Build the actor and critic networks</td>
</tr>
<tr class="even">
<td>Learning rate</td>
<td style="text-align: right;">0.0007</td>
<td>Set the RMSprop update size</td>
</tr>
<tr class="odd">
<td>Discount factor <span class="math inline">\(\gamma\)</span></td>
<td style="text-align: right;">0.99</td>
<td>Weight future rewards</td>
</tr>
<tr class="even">
<td>GAE <span class="math inline">\(\lambda\)</span></td>
<td style="text-align: right;">0.95</td>
<td>Control advantage-estimation bias and variance</td>
</tr>
<tr class="odd">
<td>Rollout length</td>
<td style="text-align: right;">20 steps</td>
<td>Update frequently using short trajectories</td>
</tr>
<tr class="even">
<td>Entropy coefficient</td>
<td style="text-align: right;">0.01</td>
<td>Encourage exploration</td>
</tr>
<tr class="odd">
<td>Value-loss coefficient</td>
<td style="text-align: right;">0.5</td>
<td>Weight critic learning</td>
</tr>
<tr class="even">
<td>Gradient limit</td>
<td style="text-align: right;">0.5</td>
<td>Stabilize optimization</td>
</tr>
<tr class="odd">
<td>RMSprop epsilon</td>
<td style="text-align: right;"><span class="math inline">\(10^{-5}\)</span></td>
<td>Improve numerical stability</td>
</tr>
<tr class="even">
<td>Advantage normalization</td>
<td style="text-align: right;">Disabled</td>
<td>Use the Stable-Baselines3 A2C default</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="why-did-the-methods-behave-differently" class="level2">
<h2 class="anchored" data-anchor-id="why-did-the-methods-behave-differently">Why did the methods behave differently?</h2>
<section id="what-the-results-directly-show" class="level3">
<h3 class="anchored" data-anchor-id="what-the-results-directly-show">What the results directly show</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>What happened in the current test</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Greedy</strong></td>
<td>Completed all 20 scenarios, but needed the most computation time</td>
</tr>
<tr class="even">
<td><strong>Dueling DQN</strong></td>
<td>Achieved the best completion rate among the learned controllers</td>
</tr>
<tr class="odd">
<td><strong>A2C</strong></td>
<td>Made no real topology changes and produced the same result as Do-Nothing</td>
</tr>
<tr class="even">
<td><strong>Double DQN variants</strong></td>
<td>Requested many nonzero actions, but few requests changed the physical topology</td>
</tr>
</tbody>
</table>
<p>These are measured results. The explanations below are possible reasons, not proven facts.</p>
</section>
<section id="possible-reasons-in-simple-terms" class="level3">
<h3 class="anchored" data-anchor-id="possible-reasons-in-simple-terms">Possible reasons in simple terms</h3>
<p><strong>Why was Greedy safe but slow?</strong><br>
When the grid became stressed, Greedy used the simulator to try the 21 candidate actions before choosing one. This made its decisions reliable, but each decision required many extra power-flow calculations.</p>
<p><strong>Why might Dueling DQN work well?</strong><br>
Dueling DQN learns two questions separately: <em>Is the current grid state safe or dangerous?</em> and <em>Which action is better in this state?</em> Most time steps were already safe, so this separation may have helped the network learn when an action was truly needed.</p>
<p><strong>Why did A2C behave like Do-Nothing?</strong><br>
Most time steps gave a positive survival reward without any switching. A2C may therefore have learned that A0 was usually the safest choice. Its short 20-step updates may also have made rare dangerous events harder to learn from.</p>
<p><strong>Why were many Double DQN requests ineffective?</strong><br>
The actions are set-point commands. If an action requests a topology that is already active, the request is nonzero but no switch occurs. The DRL input contains line status and power-flow measurements, but not the complete Busbar 1/2 assignment (<code>topo_vect</code>). The agent may therefore repeat an action because it cannot directly see that the requested topology is already active.</p>
<p><strong>Why is Greedy less affected by missing <code>topo_vect</code>?</strong><br>
Greedy obtains the full Grid2Op state and simulates each action before execution. It can observe the predicted result even when the smaller DRL input does not describe every busbar assignment explicitly.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Measured result versus possible explanation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Measured result versus possible explanation
</div>
</div>
<div class="callout-body-container callout-body">
<p>The benchmark tells us <strong>which method performed better</strong>. It does not yet prove <strong>why</strong>. For example, Dueling DQN’s design is a reasonable explanation for its result, but the current single-seed experiment cannot prove that the Dueling architecture caused the improvement.</p>
</div>
</div>
</section>
<section id="how-to-check-these-explanations" class="level3">
<h3 class="anchored" data-anchor-id="how-to-check-these-explanations">How to check these explanations</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Question</th>
<th>Simple follow-up test</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Is Dueling DQN consistently better?</td>
<td>Train each method with at least three seeds</td>
</tr>
<tr class="even">
<td>Does missing topology information cause repeated requests?</td>
<td>Add <code>topo_vect</code> and train again</td>
</tr>
<tr class="odd">
<td>Is an algorithm stuck on one action?</td>
<td>Count how often it selects A0–A20</td>
</tr>
<tr class="even">
<td>Does a switch actually improve the grid?</td>
<td>Compare maximum <span class="math inline">\(\rho\)</span> before and after each switch</td>
</tr>
<tr class="odd">
<td>Can repeated commands be reduced?</td>
<td>Mask an already-active action or add a small request penalty</td>
</tr>
</tbody>
</table>
<p>Until these tests are completed, the performance differences are confirmed, but their causes should be presented as possible explanations.</p>
</section>
</section>
<section id="evaluation-metrics" class="level2">
<h2 class="anchored" data-anchor-id="evaluation-metrics">Evaluation metrics</h2>
<p>The methods are evaluated using six complementary indicators:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Interpretation</th>
<th>Desired direction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Completion Rate</strong></td>
<td>Percentage of test episodes completing all 2,016 steps</td>
<td>Higher</td>
</tr>
<tr class="even">
<td><strong>Blackout Rate</strong></td>
<td>Percentage of episodes ending early because the grid can no longer operate</td>
<td>Lower</td>
</tr>
<tr class="odd">
<td><strong>Mean Episode Length</strong></td>
<td>Average number of operating steps completed</td>
<td>Higher</td>
</tr>
<tr class="even">
<td><strong>Overload-Step Ratio</strong></td>
<td>Percentage of operating steps with at least one overloaded line</td>
<td>Lower</td>
</tr>
<tr class="odd">
<td><strong>Mean Actual Switching Steps</strong></td>
<td>Average number of time steps in which topology is actually changed</td>
<td>Context dependent</td>
</tr>
<tr class="even">
<td><strong>Mean Inference Time</strong></td>
<td>Average computation time required to select one action</td>
<td>Lower</td>
</tr>
</tbody>
</table>
</section>
<section id="key-results" class="level2">
<h2 class="anchored" data-anchor-id="key-results">Key results</h2>
<div class="result-grid">
<div class="result-card">
<div class="result-number">
100%
</div>
<div class="result-title">
Greedy completion rate
</div>
<div class="result-text">
Highest security performance in the benchmark.
</div>
</div>
<div class="result-card">
<div class="result-number">
95%
</div>
<div class="result-title">
Dueling DQN completion rate
</div>
<div class="result-text">
Best-performing DRL method.
</div>
</div>
<div class="result-card">
<div class="result-number">
0.055%
</div>
<div class="result-title">
Dueling DQN overload ratio
</div>
<div class="result-text">
Second lowest overload burden after Greedy.
</div>
</div>
<div class="result-card">
<div class="result-number">
0.781 ms
</div>
<div class="result-title">
Dueling DQN inference time
</div>
<div class="result-text">
Sub-millisecond online action selection.
</div>
</div>
</div>
<div class="figure-panel">
<p><img src="images/performance_metrics.png" class="img-fluid" style="width:100.0%" alt="Comparison of completion rate, overload burden, and safety-computation trade-off across topology-control methods"></p>
</div>
<p>The figure summarizes three aspects of performance:</p>
<p><strong>a. Episode completion rate.</strong> Higher is better. Greedy reaches 100%, while Dueling DQN is the strongest DRL method at 95%.</p>
<p><strong>b. System overload burden.</strong> Lower is better. Greedy has the lowest overload-step ratio (0.0446%), followed by Dueling DQN (0.0550%).</p>
<p><strong>c.&nbsp;Safety–computation trade-off.</strong> A favorable method combines high completion rate with low inference time. Dueling DQN provides the strongest safety–speed balance among the DRL methods, whereas Greedy is safer but substantially slower in this benchmark.</p>
<div class="mini-note">
<p><strong>Benchmark note:</strong> the supplied comparison figure reports seed = 0, 20 fixed held-out seven-day chronics, and 2,016 steps per chronic. The error bars in panel (a) are Wilson 95% intervals across chronics and do not represent training-seed uncertainty.</p>
</div>
</section>
<section id="detailed-performance" class="level2">
<h2 class="anchored" data-anchor-id="detailed-performance">Detailed performance</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th style="text-align: right;">Completion Rate</th>
<th style="text-align: right;">Blackout Rate</th>
<th style="text-align: right;">Mean Episode Length</th>
<th style="text-align: right;">Overload-Step Ratio</th>
<th style="text-align: right;">Mean Actual Switching Steps</th>
<th style="text-align: right;">Mean Inference Time</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Greedy</strong></td>
<td style="text-align: right;"><strong>100%</strong></td>
<td style="text-align: right;"><strong>0%</strong></td>
<td style="text-align: right;"><strong>2016.0</strong></td>
<td style="text-align: right;"><strong>0.0446%</strong></td>
<td style="text-align: right;">13.15</td>
<td style="text-align: right;">38.195 ms</td>
</tr>
<tr class="even">
<td><strong>Dueling DQN</strong></td>
<td style="text-align: right;"><strong>95%</strong></td>
<td style="text-align: right;"><strong>5%</strong></td>
<td style="text-align: right;">1978.4</td>
<td style="text-align: right;"><strong>0.0550%</strong></td>
<td style="text-align: right;">15.55</td>
<td style="text-align: right;">0.781 ms</td>
</tr>
<tr class="odd">
<td>DQN</td>
<td style="text-align: right;">90%</td>
<td style="text-align: right;">10%</td>
<td style="text-align: right;">1961.2</td>
<td style="text-align: right;">0.0750%</td>
<td style="text-align: right;"><strong>8.60</strong></td>
<td style="text-align: right;"><strong>0.266 ms</strong></td>
</tr>
<tr class="even">
<td>PPO</td>
<td style="text-align: right;">80%</td>
<td style="text-align: right;">20%</td>
<td style="text-align: right;">1767.8</td>
<td style="text-align: right;">0.0591%</td>
<td style="text-align: right;">30.00</td>
<td style="text-align: right;">0.505 ms</td>
</tr>
<tr class="odd">
<td>Double DQN</td>
<td style="text-align: right;">75%</td>
<td style="text-align: right;">25%</td>
<td style="text-align: right;">1746.1</td>
<td style="text-align: right;">0.2560%</td>
<td style="text-align: right;">40.75</td>
<td style="text-align: right;">0.905 ms</td>
</tr>
<tr class="even">
<td>A2C</td>
<td style="text-align: right;">70%</td>
<td style="text-align: right;">30%</td>
<td style="text-align: right;">1646.3</td>
<td style="text-align: right;">0.0889%</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.500 ms</td>
</tr>
<tr class="odd">
<td>Do-Nothing</td>
<td style="text-align: right;">70%</td>
<td style="text-align: right;">30%</td>
<td style="text-align: right;">1646.3</td>
<td style="text-align: right;">0.0889%</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.001 ms</td>
</tr>
<tr class="even">
<td>Dueling Double DQN</td>
<td style="text-align: right;">10%</td>
<td style="text-align: right;">90%</td>
<td style="text-align: right;">1045.9</td>
<td style="text-align: right;">0.7371%</td>
<td style="text-align: right;">73.25</td>
<td style="text-align: right;">0.743 ms</td>
</tr>
</tbody>
</table>
</section>
<section id="mechanism-level-diagnostic-analysis" class="level2">
<h2 class="anchored" data-anchor-id="mechanism-level-diagnostic-analysis">Mechanism-level diagnostic analysis</h2>
<p>The aggregate benchmark identifies the strongest methods but does not explain why an episode succeeds or fails. A second evaluation therefore recorded one diagnostic row at every five-minute step for five representative controllers: Do-Nothing, Greedy, DQN, Dueling DQN, and PPO. The log contains the selected action, affected substation, maximum line-loading ratio, overloaded-line IDs, actual topology changes, line disconnections, illegal-action flags, terminal exceptions, and inference time.</p>
<section id="what-the-20-test-scenarios-represent" class="level3">
<h3 class="anchored" data-anchor-id="what-the-20-test-scenarios-represent">What the 20 test scenarios represent</h3>
<p>Each test scenario is a pre-existing Grid2Op chronic directory containing one seven-day sequence of generation and load values. For example, <code>0851</code> identifies the folder <code>chronics/0851</code>; it is a dataset identifier, not a random seed or difficulty score. The 20 fixed held-out scenarios used here were</p>
<pre class="text"><code>0009, 0033, 0153, 0207, 0275, 0301, 0315, 0411, 0443, 0513,
0561, 0573, 0685, 0715, 0818, 0851, 0881, 0900, 0903, 0998.</code></pre>
<p>The underlying generation and load trajectories are read from the stored CSV files; they are not regenerated during evaluation. All methods start from the same scenario and use the same exogenous time series, enabling paired scenario-level comparison.</p>
</section>
<section id="scenario-outcomes-action-efficiency-and-terminal-failures" class="level3">
<h3 class="anchored" data-anchor-id="scenario-outcomes-action-efficiency-and-terminal-failures">Scenario outcomes, action efficiency, and terminal failures</h3>
<div class="figure-panel">
<p><img src="images/case14_diagnostic_summary.png" class="img-fluid" style="width:100.0%" alt="Scenario-level completion matrix, nonzero action requests versus actual switching, and terminal failure categories for five Case14 controllers"></p>
</div>
<p>Panel <strong>a</strong> shows which controllers completed each seven-day chronic. Greedy rescued all six Do-Nothing failures. Dueling DQN rescued five without creating a new failure, whereas DQN rescued five baseline failures but failed in Scenario 0033, which Do-Nothing completed. PPO rescued two baseline failures.</p>
<p>Panel <strong>b</strong> distinguishes an <strong>action request</strong> from an <strong>actual switching step</strong>. At each five-minute step, the controller selects exactly one of A0–A20. Selecting A1–A20 counts as one nonzero request. It counts as an actual switching step only if the network topology or line status physically changes after execution. One requested action may set several devices within one substation, but the controller cannot request two sequential actions within the same five-minute step.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th style="text-align: right;">Nonzero requests per episode</th>
<th style="text-align: right;">Actual switching steps per episode</th>
<th style="text-align: right;">Request-to-switch effectiveness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Greedy</td>
<td style="text-align: right;">13.15</td>
<td style="text-align: right;">13.15</td>
<td style="text-align: right;">100.000%</td>
</tr>
<tr class="even">
<td>Dueling DQN</td>
<td style="text-align: right;">1959.40</td>
<td style="text-align: right;">15.55</td>
<td style="text-align: right;">0.794%</td>
</tr>
<tr class="odd">
<td>DQN</td>
<td style="text-align: right;">1960.10</td>
<td style="text-align: right;">8.60</td>
<td style="text-align: right;">0.439%</td>
</tr>
<tr class="even">
<td>PPO</td>
<td style="text-align: right;">1767.75</td>
<td style="text-align: right;">30.00</td>
<td style="text-align: right;">1.697%</td>
</tr>
<tr class="odd">
<td>Do-Nothing</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">Not applicable</td>
</tr>
</tbody>
</table>
<p>Request-to-switch effectiveness is defined as</p>
<p><span class="math display">\[
\eta_{\mathrm{action}} =
\frac{N_{\mathrm{actual\ switching\ steps}}}
{N_{\mathrm{nonzero\ requests}}}\times100\%.
\]</span></p>
<p>The low DRL values do not mean that multiple actions were executed every five minutes. Instead, the learned policies repeatedly selected set-point actions whose target topology was already active. The present reward penalizes actual switching, but it does not directly penalize a repeated nonzero request that leaves the topology unchanged. Greedy avoids this pattern because it selects A0 under low stress and requests a nonzero action only when its one-step search selects a physical topology change.</p>
<p>Panel <strong>c</strong> reports the terminal exceptions. Most blackout episodes ended with AC power-flow non-convergence. This exception describes how Grid2Op stopped, not necessarily the complete initiating mechanism; the preceding overload, disconnection, and action sequence must also be examined.</p>
</section>
<section id="representative-overload-trajectories" class="level3">
<h3 class="anchored" data-anchor-id="representative-overload-trajectories">Representative overload trajectories</h3>
<div class="figure-panel">
<p><img src="images/case14_representative_trajectories.png" class="img-fluid" style="width:100.0%" alt="Maximum line-loading trajectories for Scenarios 0275, 0033, and 0851 with topology-switch and blackout markers"></p>
</div>
<p>Each curve reports the maximum line-loading ratio observed before the next action,</p>
<p><span class="math display">\[
\rho_{\max,t}=\max_i(\rho_{i,t}).
\]</span></p>
<p>The red dashed line marks the overload threshold ( <span class="math inline">\(\rho=1\)</span>), circles mark actual topology switches, and an <code>X</code> marks blackout termination. Scenario 0275 illustrates a baseline failure rescued by both DQN variants. Scenario 0033 isolates a DQN-specific failure. Scenario 0851 is the hardest example in this subset: only Greedy completed all 2,016 steps.</p>
</section>
<section id="dqn-failure-sequence-in-scenario-0033" class="level3">
<h3 class="anchored" data-anchor-id="dqn-failure-sequence-in-scenario-0033">DQN failure sequence in Scenario 0033</h3>
<p>The DQN failure classification was taken from the Grid2Op step log rather than inferred from the completion curve alone.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 36%">
<col style="width: 36%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Step</th>
<th style="text-align: right;">Selected action</th>
<th>Logged event</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1669</td>
<td style="text-align: right;">A17</td>
<td>Line 9 was slightly overloaded; the grid continued operating.</td>
</tr>
<tr class="even">
<td style="text-align: right;">1670</td>
<td style="text-align: right;">A9</td>
<td>Lines 9 and 13 changed to disconnected status; maximum loading rose from approximately 1.00 to 1.86.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1671</td>
<td style="text-align: right;">A2</td>
<td>Grid2Op rejected the request as illegal because it affected the status of more than one line (<code>[9, 13]</code>); the episode did not yet terminate.</td>
</tr>
<tr class="even">
<td style="text-align: right;">1672</td>
<td style="text-align: right;">A2</td>
<td>The illegal-action warning recurred and the AC power flow failed to converge after ten Newton–Raphson iterations.</td>
</tr>
</tbody>
</table>
<p>Across the complete 20-scenario diagnostic run, DQN produced two illegal-action flags, both in Scenario 0033. Do-Nothing, Greedy, Dueling DQN, and PPO produced none. An illegal request is normally ignored by Grid2Op and therefore should not be interpreted as proof that the request alone caused the blackout. A more bounded interpretation is that the grid had already entered a severely stressed post-disconnection state, and the repeated illegal request failed to provide a feasible recovery action before power-flow non-convergence.</p>
</section>
<section id="overload-is-not-identical-to-blackout" class="level3">
<h3 class="anchored" data-anchor-id="overload-is-not-identical-to-blackout">Overload is not identical to blackout</h3>
<p>A line is overloaded when ( <span class="math inline">\(\rho &gt; 0.90\)</span>), but this does not necessarily terminate the episode. Grid2Op tracks consecutive overload duration for each line and may disconnect a line after the allowed duration, or immediately under sufficiently severe overload. The remaining network is then solved again. The episode ends only if the resulting grid can no longer be operated, for example because of cascading disconnections, islanding, or power-flow non-convergence. This is why Greedy can show a small nonzero overload-step ratio while still achieving zero blackouts in the current 20 scenarios.</p>
</section>
</section>
<section id="interpretation-limits-and-next-validation-steps" class="level2">
<h2 class="anchored" data-anchor-id="interpretation-limits-and-next-validation-steps">Interpretation limits and next validation steps</h2>
<p>The mechanism logs deepen the seed-0 comparison, but they do not yet establish that a particular neural architecture intrinsically causes the observed ranking. The current evidence is limited to one training seed and 20 of approximately 152 held-out test chronics. In particular, Dueling DQN’s value–advantage decomposition is a plausible reason for its strong performance when many actions have similar or redundant effects, but that explanation remains a hypothesis until it is tested across multiple seeds and controlled ablations.</p>
<p>The next validation stage should therefore:</p>
<ol type="1">
<li>train DQN, Dueling DQN, and PPO with at least seeds 0–2;</li>
<li>evaluate each trained model on the complete fixed test split;</li>
<li>report paired scenario outcomes and confidence intervals;</li>
<li>compare the original policy with an invalid/redundant-action mask or a small repeated-request penalty;</li>
<li>classify failure sequences into persistent overload, protection-driven line loss, illegal action, islanding, and power-flow non-convergence.</li>
</ol>
</section>
<section id="main-findings" class="level2">
<h2 class="anchored" data-anchor-id="main-findings">Main findings</h2>
<div class="callout callout-style-default callout-tip callout-titled" title="Takeaway 1 — Best overall security">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Takeaway 1 — Best overall security
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Greedy</strong> achieves the highest episode completion rate and the lowest overload burden, making it the strongest security benchmark in the current comparison.</p>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Takeaway 2 — Best DRL method">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Takeaway 2 — Best DRL method
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Dueling DQN</strong> is the strongest DRL method, reaching a 95% completion rate and a 0.0550% overload-step ratio while maintaining sub-millisecond inference time.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Takeaway 3 — Fast DRL decision making">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Takeaway 3 — Fast DRL decision making
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>DQN</strong> has the lowest inference overhead among the tested DRL methods and requires fewer actual topology-switching steps than the other active DRL controllers in the supplied results.</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled" title="Takeaway 4 — Policy instability">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Takeaway 4 — Policy instability
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Dueling Double DQN</strong> performs poorly in the supplied benchmark, with a 10% completion rate, 90% blackout rate, and the highest overload-step ratio, indicating significant policy instability in this experiment.</p>
</div>
</div>
</section>
<section id="research-message" class="level2">
<h2 class="anchored" data-anchor-id="research-message">Research message</h2>
<p>This benchmark demonstrates a clear distinction between <strong>maximum security performance</strong> and <strong>fast learned decision making</strong>. Greedy provides the strongest overall security, whereas Dueling DQN offers the most competitive DRL balance between episode survival, overload mitigation, and online inference speed.</p>
<hr>
<p><em>This page is structured as a research showcase: <strong>problem → system → method → benchmark → results → findings</strong>. It can be expanded later with additional training seeds, hyperparameter ablations, the complete held-out test split, or larger power-grid cases.</em></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Research showcase built with Quarto</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>